package easy

/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

fun findTheDifference(s: String, t: String): Char {
    val arrS = s.toCharArray()
    val arrT = t.toCharArray()
    var result: Char? = null
    arrS.sort()
    arrT.sort()
    for (i in 0 until arrT.size) {
        if (i == arrT.lastIndex || arrT[i] != arrS[i]) {
            result = arrT[i]
            break
        }
    }
    return result!!
}